name: Bug Bounty Trend Tracker

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  track_trends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pandas openai markdownify

      - name: Fetch and Analyze Bug Bounty Reports
        run: python scripts/trend_tracker.py

      - name: Commit and Push Report
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add reports/latest_trends.md
          git commit -m "Update bug bounty trends report" || echo "No changes to commit"
          git push
