name: Bug Bounty Trends

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12 PM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track_trends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Initialize Go Module
        run: |
          if [ ! -f "go.mod" ]; then
            go mod init github.com/${{ github.repository }}
          fi

      - name: Install Dependencies
        run: go mod tidy

      - name: Fetch and Analyze Bug Bounty Trends
        run: go run main.go

      - name: Commit and Push Report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add trends.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated Bug Bounty Trends"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
